[project]
name = "dcmv"
version = "0.1.0"
description = "A safety vision system to protect peope inside molding machines"
readme = "README.org"
requires-python = ">=3.13"
dependencies = [
	# "ultralytics",
	"opencv-python",

]

[tool.uv.workspace]
members = [
	"dcmv",
]
